defaults: &defaults
  twitter: voxe
  google_analytics:
    id: UA-28225427-1

test:
  <<: *defaults
  host: localhost:3000

development:
  <<: *defaults
  host: localhost:3000
  facebook:
    app_id: 341867925824593
    app_secret: ea003ded7c30733dfb52996c4cedea7d
  
production:
  <<: *defaults
  host: voxe.org
  facebook:
    app_id: 166791223426274
    app_secret: 008bba7f5ac39ad759af5dcce99fa647
  
staging:
  <<: *defaults
  host: staging.voxe.org
  facebook:
    app_id: 339716929372553
    app_secret: 34e6c9cb8ade129d5ddd3e4dadfeace1