development:
  sessions:
    default:
      database: voxe
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: voxe_test
      hosts:
        - localhost:27017

staging:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
