development:
  host: localhost
  database: voxe

test:
  host: localhost
  database: joinplato_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>

staging:
  uri: <%= ENV['MONGOHQ_URL'] %>
