-
  namespace: pierrev
  name: Pierre Valade
  info: "co-fondateur & product"
  description: "En exil à New York, Pierre est aussi UX designer chez foursquare."
-
  namespace: edouards
  name: Edouard Schlumberger
  info: co-fondateur
  description: "Edouard est co-fondateur de Voxe.org, porte-parole et animateur des équipes. <br /> Et ce n’est pas un “full time Job”." 
-
  namespace: benjaminlsl
  name: Benjamin Lan Sun Luk
  info: "back-end & api"
  description:
-
  namespace: charlotter
  name: Charlotte Richard
  info: presse
  description: ''
-
  namespace: juliab
  name: Julia Bijaoui
  info: partenariats
  description: "En charge des partenariats et des évènements. Julia a fondé le Prix Littéraire des Grandes Ecoles à 21 ans (avant même de savoir repasser une chemise). Etudiante à HEC et elle vit une torride  histoire  avec les médias sociaux, les start-up et la littérature. Julia est actrice dans une autre vie et fan de karaoké à ses heures perdues."
-
  namespace:
  name: Paul Chobert
  info: front-end
  description: ''
-
  namespace: pierreyvesr
  name: Pierre-Yves Ricaud
  info: android
  description: "Pierre-Yves, notre mage d’Android, ne peut coder sans la Chaîne Parlementaire en fond sonore. Pour le rendre heureux : nourrissez-le de pâtes au Kiri et de Open Source software. Piwaï est diplômé de KTH Royal Institute of Technology (Suède) et de l’Insa Rouen."
-
  namespace: katb
  name: Kat Borlongan
  info: international
  description: ''
-
  namespace:
  name: Thibault Geffroy
  info: design
  description: ''
-
  namespace:
  name: Antoine Maillard
  info: iOS
  description: ''
-
  namespace:
  name: Anatole Royer
  info: design
  description: ''
-
  namespace: benjaminn
  name: Benjamin Netter
  info: web
  description: ''