-
  namespace: pierrev
  name: Pierre Valade
  info: "co-fondateur & product"
  description: "En exil à New York, Pierre est aussi UX designer chez foursquare."
-
  namespace: edouards
  name: Edouard Schlumberger
  info: "co-fondateur & marketing"
  description: "Edouard est co-fondateur de Voxe.org, porte-parole et animateur des équipes. <br /> Et ce n’est pas un “full time Job”." 
-
  namespace: benjaminlsl
  name: Benjamin Lan Sun Luk
  info: "back-end & api"
  description: "Benjamin a créé l’API de Voxe.org et travaille sur notre back-office. Il est aussi connu pour développer plus vite que son ombre."
-
  namespace: charlotter
  name: Charlotte Richard
  info: communication
  description: "Charlotte est la pro de la com’. Grâce à un carnet d’adresse long comme le bras, tout le monde connaît Voxe.org. Et Charlotte."
-
  namespace: juliab
  name: Julia Bijaoui
  info: partenariats
  description: "Julia signe les partenariats et organise les événements de Voxe.org. Hackathon kesako ? Elle vous explique tout."
-
  namespace: paulc
  name: Paul Chobert
  info: front-end
  description: "Paul développe notre back-office et plein d'autres choses, et aime déployer son code vers 6 heures du matin, pas avant."
-
  namespace: pierreyvesr
  name: Pierre-Yves Ricau
  info: android
  description: "Il développe l'application Android du comparateur avec la chaîne parlementaire en fond sonore. Si si."
-
  namespace: katb
  name: Kat Borlongan
  info: international
  description: "Kat, polyglotte et née aux Philippines, promeut la plateforme à l’international. Pas le choix, elle ne vote pas en France ;-)"
-
  namespace: thibaultg
  name: Thibault Geffroy
  info: design
  description: "Thibault réalise les visuels et icônes de Voxe.org. Il paraît qu’il est pictogramophile."
-
  namespace:
  name: Antoine Maillard
  info: iOS
  description: "Antoine a créé notre application iPhone/iPad. Oui, en effet, c’est impressionnant."
-
  namespace:
  name: Anatole Royer
  info: design
  description: "Anatole est notre artiste. L’inspiration et le logo, c’est lui!"
-
  namespace: benjaminn
  name: Benjamin Netter
  info: web
  description: "Benjamin est un de nos UX designers front-end. Vous trouvez que Voxe.org, c’est joli ? C’est normal."
-
  namespace: romainl
  name: Romain Lalanne
  info: media sociaux
  description: "Romain travaille la présence de Voxe.org sur les medias sociaux. C’est le dernier arrivé !"
